### ISSUE TITLE
WD possible false positive.

### ISSUE THREAD

**Issue by a-sporez** [tamtaasatiani/tahmlib#13]
The latest build gets quarantined by Windows Defender. Scan returns Trojan:Win32/Phonzy.B!ml , the previous build did not have that issue.

**Comment by a-sporez** [comment]
Trojan:Win32/Phonzy.B!ml on the second scan.

**Comment by tamtaasatiani** [comment]
did you make the previous build a few hours ago? because i haven't changed the repository in a few days

**Comment by tamtaasatiani** [comment]
also, that message could mean a false positive, apparently ( https://www.reddit.com/r/antivirus/comments/17c3opf/trojanwin32phonzybml/ )
could you please submit it as a false positive so it can get a human review? (as explained in the reddit thread)

**Comment by a-sporez** [comment]
The first build was right when you made the video on Youtube. The one WD flags positive was about an hour ago. I will send it for analysis.

**Comment by tamtaasatiani** [comment]
okay, i will roll the repo back just in case

**Comment by a-sporez** [comment]
I sent it to WDSI, I will keep you updated on the response, I believe it's because of tahmlib/Debug/tahm.exe.

**Comment by tamtaasatiani** [comment]
it's just the executable. it gets generated while debugging. someone must've left it in there while adding features.
try deleting the executable and scanning again

**Comment by a-sporez** [comment]
I updated the name of the issue, pretty sure it's false positive. I glanced upon the decompiled .exe with a list of bad keywords and it seems fine, but reverse engineering is just a hobby I'm not a pro. Random executables in a pull request is not desirable though, I'd be happy to keep looking for them in future pulls.

**Comment by tamtaasatiani** [comment]
i deleted the .exe file and added .exe to gitignore to make sure the same problem doesn't arise in the future. closing this issue to let others know it is resolved for now
