### ISSUE TITLE
"main" function needs to be revised

### ISSUE THREAD

**Issue by tamtaasatiani** [tamtaasatiani/tahmlib#5]
Game loop should be moved inside the "tahm" class

**Comment by Javier-Lozano** [comment]
Hi, this is my first ever contribution to someone else's project, so I don't really know how to post the changes.

First of all as an annoying Linux user I am obliged to tell you I'm using Linux and was able to compile the code and if I'm breaking something for Windows users that might be the reason.

**tahm.h**
I added ` void run()` and moved `void handleEvents()` inside the Tham class
```
class Tham
{
public:
	void run();
private:
	void handleEvents();
...
}
```

**tahm.cpp**

Included `engine.h` to access `start()`, `update()`, `draw() `and `keypressed()`. The main loop now runs inside `Tahm::run()`
```
#include "tahm.h"
#include "../engine.h"

//...

void Tahm::init(void)
{
	start();
	window->init();
	renderer->init();
	audio->setupDevice();
}

void Tahm::run(void)
{
	while (running)
	{
		handleEvents();
		update();
		renderer->prepare();
		draw();
		renderer->present();
		SDL_Delay(16);
	}
}

void Tahm::handleEvents()
{
	Event event;
	while (SDL_PollEvent(&event))
	{
		switch (event.type)
		{
		case SDL_QUIT:
			running = false;
			break;

		case SDL_KEYDOWN:
			keypressed(event);
			break;

		default:
			break;
		}
	}

}

```

**engine.cpp**

This is how main() function look like now, much more cleaner
```

int main(int argc, char* argv[])
{
	tahm.init();
	tahm.run();
	tahm.destroy();

	return 0;
}

```
**engine.h** 

A global variable was declared inside engine.cpp  so I added this
`extern Tahm& tahm;`
and  unless some fancy C/C++ trickery is being at work I removed prototype for main() function.
